KP_CONSTANT_THROTTLE = 0.25
KI_CONSTANT_THROTTLE = 0.15
KD_CONSTANT_THROTTLE = 0.1

KP_CONSTANT_POS= 0.1
KI_CONSTANT_POS = 0
KD_CONSTANT_POS = 0.15

KP_CONSTANT_THETA= 0.15
KI_CONSTANT_THETA = 0
KD_CONSTANT_THETA = 0
