ENGINE_DRYMASS = 20 #kg
ENGINE_FULL_MASS = 47 #kg
EXHAUST_VELOCITY = 1722.44 #m/s

ENGINE_BURN_DURATION = 15 #s
DT_THRUST_CURVE = 0.2 #s
THRUST_CURVE_VALUE = (ENGINE_FULL_MASS - ENGINE_DRYMASS) * EXHAUST_VELOCITY / ENGINE_BURN_DURATION

LENGTH = 0.5 #m
